version: '3.8'

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=master_key
    ports:
      - "7700:7700"
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped
